export const ROLE_CRUD = 'role.crud'
export const ROLE_GET = 'role.get'
export const ROLE_CREATE = 'role.create'
export const ROLE_UPDATE = 'role.update'
export const ROLE_DELETE = 'role.delete'

export const USER_CRUD = 'user.crud'
export const USER_GET = 'user.get'
export const USER_CREATE = 'user.create'
export const USER_UPDATE = 'user.update'
export const USER_DELETE = 'user.delete'

export const PERMISSION_CRUD = 'permission.crud'
export const PERMISSION_GET = 'permission.get'
export const PERMISSION_CREATE = 'permission.create'
export const PERMISSION_UPDATE = 'permission.update'
export const PERMISSION_DELETE = 'permission.delete'

export const BANK_CRUD = 'bank.crud'
export const BANK_GET = 'bank.get'
export const BANK_CREATE = 'bank.create'
export const BANK_UPDATE = 'bank.update'
export const BANK_DELETE = 'bank.delete'

export const DEPOSIT_CRUD = 'deposit.crud'
export const DEPOSIT_GET = 'deposit.get'
export const DEPOSIT_CREATE = 'deposit.create'
export const DEPOSIT_UPDATE = 'deposit.update'
export const DEPOSIT_DELETE = 'deposit.delete'
export const DEPOSIT_SHOW_TYPE = 'deposit.show_type'
export const DEPOSIT_RESEND_CALLBACK = 'deposit.resend_callback'
export const DEPOSIT_MANUAL = 'deposit.manual'
export const DEPOSIT_VERIFY = 'deposit.verify'

export const BANK_TRANSACTION_CRUD = 'bank_transaction.crud'
export const BANK_TRANSACTION_GET = 'bank_transaction.get'
export const BANK_TRANSACTION_CREATE = 'bank_transaction.create'
export const BANK_TRANSACTION_UPDATE = 'bank_transaction.update'
export const BANK_TRANSACTION_DELETE = 'bank_transaction.delete'

export const SETTING_CRUD = 'setting.crud'
export const SETTING_GET = 'setting.get'
export const SETTING_CREATE = 'setting.create'
export const SETTING_UPDATE = 'setting.update'
export const SETTING_DELETE = 'setting.delete'

export const WITHDRAWAL_CRUD = 'withdrawal.crud'
export const WITHDRAWAL_GET = 'withdrawal.get'
export const WITHDRAWAL_CREATE = 'withdrawal.create'
export const WITHDRAWAL_UPDATE = 'withdrawal.update'
export const WITHDRAWAL_DELETE = 'withdrawal.delete'
export const WITHDRAWAL_MULTIPLE_AUTO = 'withdrawal.withdrawal_multiple_auto'
export const WITHDRAWAL_AUTO = 'withdrawal.auto'
export const WITHDRAWAL_CREATE_MULTIPLE = 'withdrawal.create_multiple'
export const WITHDRAWAL_RESEND_CALLBACK = 'withdrawal.resend_callback'
export const WITHDRAWAL_MANUAL = 'withdrawal.manual'
export const WITHDRAWAL_UPDATE_STATUS = 'withdrawal.update_status'

export const BALANCE_SHOW = 'balance.show'

export const CASHOUT_CRUD = 'cashout.crud'
export const CASHOUT_GET = 'cashout.get'
export const CASHOUT_CREATE = 'cashout.create'
export const CASHOUT_UPDATE = 'cashout.update'
export const CASHOUT_DELETE = 'cashout.delete'

export const CARD_TRANSACTION_CRUD = 'card_transaction.crud'
export const CARD_TRANSACTION_GET = 'card_transaction.get'
export const CARD_TRANSACTION_CREATE = 'card_transaction.create'
export const CARD_TRANSACTION_UPDATE = 'card_transaction.update'
export const CARD_TRANSACTION_DELETE = 'card_transaction.delete'

export const VIRTUAL_TRANSACTION_CRUD = 'virtual_transaction.crud'
export const VIRTUAL_TRANSACTION_GET = 'virtual_transaction.get'
export const VIRTUAL_TRANSACTION_CREATE = 'virtual_transaction.create'
export const VIRTUAL_TRANSACTION_UPDATE = 'virtual_transaction.update'
export const VIRTUAL_TRANSACTION_DELETE = 'virtual_transaction.delete'

export const SUMMARY_GET = 'summary.get'
